from poem_plugins.general.versions import Version
from poem_plugins.general.versions.drivers import IVervsionDriver


def test_get_version(
    git_long_version_driver: IVervsionDriver, expected_version: Version,
) -> None:
    assert git_long_version_driver.get_version() == expected_version


def test_render_version(
    git_long_version_driver: IVervsionDriver, expected_version: Version,
) -> None:
    content = git_long_version_driver.render_version_file(expected_version)
    expected = "\n".join(
        (
            '# THIS FILE WAS GENERATED BY "poem_plugins.general.versions.drivers.git.GitLongVersionDriver"',
            "# NEWER EDIT THIS FILE MANUALLY",
            "",
            "version_info = (1, 2, 0)",
            '__version__ = "1.2.0+gg3c3e199"',
            "",
        ),
    )
    assert content == expected
